### PR TITLE
uh

### PR DESCRIPTION
**Pull request by darkdarcool**
you don't need that because it isn't necessary for html.

### CODE REVIEW

**Comment by JBYT27** [comment]
okie, but if you use flask, or just HTML by itself, you can do that, or use variables. like glitch studios

**Comment by JBYT27** [comment]
im pretty sure. i might be wrong

**Comment by darkdarcool** [comment]
oh, uh. ok. but you might wanna change the way to print vars

**Comment by darkdarcool** [comment]
also can you invite me to this? I have some ideas that will help!(like href stuff :)   )

**Comment by JBYT27** [comment]
hmmm, maybe (sorry), ill think about it. I'll prob inv you tho ;)

**Comment by darkdarcool** [comment]
okieeee

**Pull request closed without merging**
